### ISSUE TITLE
Solaron/Solarized Light scheme for IDE X

### ISSUE THREAD

**Issue by stupalov** [we3geeks/komodo-color-schemes#11] opened 2016-12-25 11:38 UTC
Hi,

 this is not issue, but request / offer for make Solaron/Solarized Light fully compatible with Komodo 10.
Currently as I see only Interface/widgets need to be added to scheme file(s).

In Komodo 10 completely abandoned all Light schemes, and I see you make great work with adopt this schemes for Komodo.

**Comment by we3geeks** [comment] 2016-12-31 14:48
@landy2005 This has been on my own to-do list for a couple of months now; I will take this on.

**Comment by we3geeks** [comment] 2017-01-09 12:42
@landy2005 See https://github.com/we3geeks/komodo-color-schemes/commit/27662f611eff9fbdcaba90ac79a561ac5294c1fd

It is a first version of Solaron-Light with UI support for Komodo v10; there are a couple of areas that I am not completely happy with, but it is complete enough that I would like some feedback if you are open to using it for a bit.

![komodo-solaron-light-20170109-a](https://cloud.githubusercontent.com/assets/2390335/21766904/49e4ad14-d62e-11e6-9b47-fb967dcff421.png)

**Comment by Defman21** [comment] 2017-01-09 16:50
Looks good! :)

**Comment by stupalov** [comment] 2017-01-12 20:16
@we3geeks wohoo, initially very nice!

which troubles I see:
- in ui drop-down lists merges with background
![solaron-l-b1](https://cloud.githubusercontent.com/assets/217520/21906604/5f68b636-d925-11e6-9422-f548a99cd6f6.png)
- code minimap is still dark
![solaron-l-b2](https://cloud.githubusercontent.com/assets/217520/21906605/5f6dfa88-d925-11e6-97b8-6a34cd2ae9aa.png)

tnx for your work!

**Comment by Defman21** [comment] 2017-01-12 20:20
There's no way to change the color of the visible part of your code in the sidebar: it depends on text selection color.

**Comment by we3geeks** [comment] 2017-01-14 17:20
@landy2005 Thanks for the feedback! Let me see what I can do regarding the background color on the controls on the preferences dialog. Looking at some of the other color schemes (both light and dark), I agree that those would benefit from a bit of contrast there.

**Comment by we3geeks** [comment] 2017-01-14 17:36
Thoughts?

![solaron-light-20170114-a](https://cloud.githubusercontent.com/assets/2390335/21956767/346a2bb0-da45-11e6-8e28-f2ab3fa8cc56.png)

**Comment by stupalov** [comment] 2017-01-15 14:16
> Thoughts?

exactly what is necessary :)

**Comment by we3geeks** [comment] 2017-01-15 14:18
Thanks. I will get an updated version of the scheme committed later today.

**Comment by Defman21** [comment] 2017-01-20 09:16
Nathan pointed to me that your scheme does not have background for inputs.

![image](https://cloud.githubusercontent.com/assets/7100645/22143204/45a4bdcc-df0a-11e6-9380-08ef3a0fe453.png)

**Comment by we3geeks** [comment] 2017-01-20 12:44
Is there a reason the inputs on the dialog you are showing are different than these?

![preferences](https://cloud.githubusercontent.com/assets/2390335/22149852/4408299a-ded3-11e6-83fe-5dee496e822f.png)

There is a background color specified which is a different color.

**Comment by Defman21** [comment] 2017-01-20 12:46
@Naatan?

**Comment by Naatan** [comment] 2017-01-20 15:47
Should be fine as far as the standard Komodo skinning is concerned.

**Comment by we3geeks** [comment] 2017-01-20 16:14
I'm a little confused... 

@Defman21  Is it possible your screenshot was from a version before commit https://github.com/we3geeks/komodo-color-schemes/commit/8d38e236aa16592ddf3811cc0316a58b9c4b9a64 ?

**Comment by Defman21** [comment] 2017-01-20 16:16
Nope, since I can see the fix for #12 in my Komodo :)

**Comment by Naatan** [comment] 2017-01-20 16:19
I just installed the ksf from this repo and I cannot reproduce your issue @Defman21.

**Comment by Defman21** [comment] 2017-01-20 16:21
Hmm...

**Comment by Defman21** [comment] 2017-01-20 16:23
Yeah you're right. I've downloaded Solaron again and it works fine. Sorry for false report :)

**Comment by we3geeks** [comment] 2017-01-20 16:27
No worries. I've seen occasional situations in Komodo as I've been working on getting the UI stuff into these schemes where I have to exit/restart Komodo and/or apply a different scheme and then go back to the one I'm working on in order to get all the bits and bobs to be applied, but I've not really been able to do it reliably enough to log an issue. I wonder if you got caught in one of those.

Glad someone is looking at it. :)

**Comment by Naatan** [comment] 2017-01-20 16:48
@we3geeks you might want to submit these to the Komodo Packages section, then people should get update notifications. Not to mention more people will actually be able to reap the benefits of your work :)

Instructions:

http://community.komodoide.com/packages/submit-instructions/#pane-packages

**Comment by we3geeks** [comment] 2017-01-20 17:57
@Naatan I do plan to add them there (at least the Solaron and Base16r schemes; not sure about the Minimal schemes) after I have the UI portions of the schemes addressed. I'm actually glad @landy2005  and @Defman21 pinged me: I needed a poke to get moving in that direction.

**Closed as completed** 2017-01-23 12:24 UTC
